<?php



?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Editorial Functions for Item Annotation</title>
        <link href="../bootstrap/css/bootstrap.css"  rel="stylesheet" type="text/css" />
        <link href="../bootstrap/css/bootstrap-theme.css"  rel="stylesheet" type="text/css" />
       
    </head>
    <body id="docBody">
		  <div class="container-fluid" style="padding: 0 15px;">
				<div class="row">
					 <div class="col-md-6">
						  <h1>Item Annotation</h1>
					 </div>
					 <div class="col-md-6">
						  
					 </div>
				</div>
		  </div>
	 </body>    
</html>