<?php

$genObj = new OCitems_General;
$uriObj = new infoURI;

$subjectLabel = false;
$subjectType = false;
$projectUUID = false;
$sourceID = false;
$subjectURI = false;
$subjectLocalLink = false;

$requestParams = $this->requestParams;
if(isset($requestParams["itemType"]) && $this->uuid){
	 $sRes = $uriObj->lookupOCitem($this->uuid, $requestParams["itemType"]);
	 if(is_array($sRes)){
		  $subjectLabel = $sRes["label"];
		  $subjectType = $sRes["itemType"];
		  $projectUUID = $sRes["projectUUID"];
		  $subjectURI = $genObj->generateItemURI($this->uuid, $subjectType);
		  $subjectLocalLink = $genObj->generateItemURI($this->uuid, $subjectType, false);
	 }
}

$result = $this->result;
if(is_array($result) && !$subjectLabel){
	 $subjectLabel = $result[0]["subjectLabel"];
	 $subjectType = $result[0]["subjectType"];
	 $projectUUID = $result[0]["projectUUID"];
	 $sourceID = $result[0]["sourceID"];
	 $subjectURI = $genObj->generateItemURI($this->uuid, $subjectType);
	 $subjectLocalLink = $genObj->generateItemURI($this->uuid, $subjectType, false);
}

?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Editorial Functions for Item Annotation</title>
        <link href="../../bootstrap/css/bootstrap.css"  rel="stylesheet" type="text/css" />
        <link href="../../bootstrap/css/bootstrap-theme.css"  rel="stylesheet" type="text/css" />
		  
		  <!-- general javascript -->
		  <script src="../../js/general/jquery.js" type="text/javascript" ></script>
		  <script src="../../js/general/json2.js" type="text/javascript" ></script>
        <script src="../../js/general/utils.js" type="text/javascript" ></script>
        <script src="../../js/general/prototype.js" type="text/javascript" ></script>
		  <!-- end of general javascript -->
		  <!--
		 http://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js
		 -->
		  <script src="http://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js" type="text/javascript" ></script>
		  <script src="../../js/editorial/annotations.js" type="text/javascript" ></script>
		  
    </head>
    <body id="docBody">
		  <div class="container-fluid" style="padding: 0 15px;">
				<div class="row">
					 <div class="col-md-4">
						  <h1>Item Annotation</h1>
					 </div>
					 <div class="col-md-4">
					 
					 </div>
					 <div class="col-md-4">
						  <form action="../../editorial/annotations" method="get">
								<h5>Lookup UUID</h5>
								<input name="uuid" type="text" id="in-item-uuid" value="<?php echo $this->uuid; ?>" />
								<button type="submit">Get Annotations</button>
						  </form>
					 </div>
				</div>
				<div class="row">
					 <div class="col-md-3">
						  <h4>Subject Entity Label</h4>
						  <h5><?php echo $subjectLabel; ?></h5>
					 </div>
					 <div class="col-md-3">
						  <h4>Subject Entity UUID</h4>
						  <h5><?php echo $this->uuid; ?></h5>
					 </div>
					 <div class="col-md-3">
						  <h4>Subject Entity Type</h4>
						  <h5><?php echo $subjectType; ?></h5>
					 </div>
					 <div class="col-md-3">
						  <h4>Subject Entity URI</h4>
						  <h5><a href="<?php echo $subjectLocalLink; ?>" target="_blank"><?php echo $subjectURI; ?></a></h5>
					 </div>
				</div>
				<div class="row">
					 <div class="col-md-6">
						  
					 </div>
					 <div class="col-md-6">
						  
					 </div>
				</div>
				<div class="row">
					 <div class="col-md-9">
						  <div id="annotations">
								<table class="table table-condensed table-striped table-hover">
									 <thead>
										  <th style="width:8%;">Delete</th>
										  <th style="width:16%;">Predicate Label</th>
										  <th style="width:30%;">Predicate URI</th>
										  <th style="width:16%;">Object Label</th>
										  <th style="width:30%;">Object URI</th>
									 </thead>
									 <tbody>
									 <?php
									 if(is_array($result)){
										  foreach($result as $row){
												echo "<form action=\"../edit/delete-annotation\" method=\"post\" >";
												echo "<input type=\"hidden\" name=\"uuid\" value=\"".$this->uuid."\" />";
												echo "<input type=\"hidden\" name=\"hashID\" value=\"".$row["hashID"]."\" />";
												echo "<tr id=\"".$row["hashID"]."\">".chr(13);
												echo "<td>";
												echo "<button title=\"Delete this annotation\" type=\"submit\" class=\"btn btn-warning\">X</button>";
												echo "</td>".chr(13);
												echo "<td>".$row["predicateLabel"]."</td>".chr(13);
												echo "<td>".$row["predicateURI"]."</td>".chr(13);
												echo "<td>".$row["objectLabel"]."</td>".chr(13);
												echo "<td>".$row["objectURI"]."</td>".chr(13);
												echo "</tr>".chr(13);
												echo "</form>".chr(13);
										  }
									 }
									 ?>
									 <form action="../edit/add-annotation" method="post" >
										  <input type="hidden" name="uuid" value="<?php echo $this->uuid; ?>" />
										  <input type="hidden" name="subjectType" value="<?php echo $subjectType; ?>" />
										  <input type="hidden" name="projectUUID" value="<?php echo (string)$projectUUID; ?>" />
										  <input type="hidden" name="sourceID" value="<?php echo $sourceID; ?>" />
										  <tr>
												<td><button class="btn" type="submit">+</button></td>
												<td id="add-pred-label"></td>
												<td><input onchange="javascript:getEntityByType('predicate');" class="form-control" type="text" name="predicateURI" id="add-pred-uri"/></td>
												<td id="add-obj-label"></td>
												<td><input onchange="javascript:getEntityByType('object');" class="form-control" type="text" name="objectURI" id="add-obj-uri"/></td>
										  </tr>
									  </form>
										  <tr>
												<td></td>
												<td><h5>New Predicate Entity</h5></td>
												<td><div id="add-pred-entity"></div></td>
												<td><h5>New Object Entity</h5></td>
												<td><div id="add-obj-entity"></div></td>
										  </tr>
										  <tr>
												<td></td>
												<td></td>
												<td><div id="pred-newEntityForm"></div></td>
												<td></td>
												<td><div id="obj-newEntityForm"></div></td>
										  </tr>
									 </tbody>
								</table>
						  </div>
					 </div>
					 <div class="col-md-3">
					 
					 </div>
				</div>
				<div class="row">
					 <div class="col-md-6">
						  
					 </div>
					 <div class="col-md-6">
						  
					 </div>
				</div>
		  </div>
	 </body>    
</html>