<?php

$ocGenObj = new OCitems_General;
$host = $ocGenObj->getLocalBaseURI();


?>

<div id="headerTop">
    <div id="headerTopContent">
        <div id="headerTopLogoArea">
            <div id="headerTopLogoRow">
                <div id="headerTopLogoCellImage">
                    <a href="<?php echo $host;?>" title="Open Context (Home)"><img src="<?php echo $host;?>/images/layout/oc-door-logo.png" alt="Open Context Logo"/></a>
                </div>
                <div id="headerTopLogoCellText">
                    <a href="<?php echo $host;?>" title="Open Context (Home)">Open Context</a>
                </div>
            </div>
            <div id="headerTopLogoTagLine">
                Web-based research data publication
            </div>
        </div>
        
        <div id="headerMiddleArea">
        </div>

    </div>
</div>